# Generated by Django 4.2.2 on 2023-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Codigo', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
