# Generated by Django 4.2.2 on 2023-07-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='Nombre',
            new_name='Nombre_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='Codigo',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Mensaje',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
