# Generated by Django 4.2.2 on 2023-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0002_rename_nombre_solicitud_nombre_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='Nombre_solicitud',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
