# Generated by Django 4.2.2 on 2023-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0003_alter_solicitud_nombre_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='Mensaje',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='Nombre_solicitud',
            field=models.CharField(max_length=50),
        ),
    ]
